"""Adds one fixture entry for every value of the code cases that no entry shows yet.

Reads tel-values.json and tel-cases/*.json (cprima-fork/app/sharedTest/resources) and the entries of
fixture-spec.json, which stay as they are. Writes fixture-spec.code-entries.json next to it;
fixture_spec.load_spec() appends these entries, so populate.py, check_alignment.py and ui_test.py see them.

The links an entry must show are the expected links of the code cases with that value. A value that
the fixture cannot hold (the user name, the title, the password: the fixture has the URL, the Notes and
one custom field) is listed under `unsupported`, and so is a generated value.

Run:  uv run python make_code_entries.py
"""

import glob
import json
import sys
from pathlib import Path

import fixture_spec

HERE = Path(__file__).resolve().parent
RESOURCES = HERE.parent.parent / "app" / "sharedTest" / "resources"
OUTPUT = HERE / "fixture-spec.code-entries.json"
FIELDS = ("url", "notes", "custom")


def main() -> int:
    values = {v["id"]: v for v in json.load(open(RESOURCES / "tel-values.json", encoding="utf8"))}
    cases = []
    for path in sorted(glob.glob(str(RESOURCES / "tel-cases" / "*.json"))):
        cases += json.load(open(path, encoding="utf8"))
    code_cases = [c for c in cases if c["level"] == "code"]

    base = json.loads((HERE / "fixture-spec.json").read_text(encoding="utf-8"))
    old_cases = fixture_spec.load_cases(base)
    shown = {(e["field"], fixture_spec.value_of(e, old_cases)) for e in base["entries"]}

    by_value: dict[tuple[str, str], list[dict]] = {}
    unsupported = []
    for case in code_cases:
        field = case.get("field", "url")
        value = values[case["value"]]
        if "value" not in value:
            unsupported.append({"case": case["id"], "why": "a generated value"})
            continue
        if field not in FIELDS:
            unsupported.append({"case": case["id"], "why": f"the fixture has no {field} field"})
            continue
        by_value.setdefault((field, case["value"]), []).append(case)

    entries, skipped = [], 0
    for (field, value_id), group in by_value.items():
        text = values[value_id]["value"]
        if (field, text) in shown:
            skipped += 1
            continue
        links = group[0]["expected"]["links"] if field == "url" else []
        if any(c["expected"]["links"] != group[0]["expected"]["links"] for c in group) and field == "url":
            print(f"note: {value_id}: the cases expect different links; the first is kept", file=sys.stderr)
        if links:
            underlined = ", ".join(repr(link["text"]) for link in links)
            expected = f"Underlined: {underlined}. The rest is plain."
        else:
            expected = "Nothing is underlined."
        names = ", ".join(f"{c['id']} ({', '.join(c['requirements'])})" for c in group)
        entry = {"id": f"value-{value_id}" if field == "url" else f"value-{value_id}-{field}",
                 "field": field, "value": text, "links": links,
                 "expected": f"{expected} Code cases: {names}."}
        if any(fixture_spec.is_tel(link) for link in links):  # the tap hands the link to Android: the dialer is chosen
            entry["scenarios"] = ["UI-LINK", "UI-TAP", "UI-LONGPRESS", "UI-CALL"]
        entries.append(entry)

    result = {
        "description": ("Generated by make_code_entries.py; do not edit. One entry for every value of the code "
                        "cases that no entry of fixture-spec.json shows yet. Appended by fixture_spec.load_spec()."),
        "entries": entries,
        "unsupported": unsupported,
    }
    OUTPUT.write_text(json.dumps(result, indent=2, ensure_ascii=True) + "\n", encoding="utf-8", newline="\n")
    print(f"{OUTPUT.name}: {len(entries)} entries added, {skipped} values already shown, "
          f"{len(unsupported)} cases unsupported")
    return 0


if __name__ == "__main__":
    sys.exit(main())
