"""Builds the near-life database tel-link-examples.kdbx and its spec near-life-spec.json from near-life.json.

An address book as a person keeps it: one fictional entry per way of writing a number. The stored text is
the value of tel-values.json named by `value`; the links an entry must show are the expected links of the
code cases with that value (tel-cases/*.json). The spec has the format of fixture-spec.json, so the same
scripts work on it with TEL_SPEC and TEL_DATABASE:

    uv run python make_near_life.py                      # spec and database
    $env:TEL_SPEC='near-life-spec.json'; $env:TEL_DATABASE='tel-link-examples.kdbx'
    uv run python ui_test.py                             # the run on the phone

The database is created when it is missing and brought in line by populate.py's rules otherwise.
"""

import glob
import json
import sys
from pathlib import Path

from pykeepass import PyKeePass, create_database

HERE = Path(__file__).resolve().parent
RESOURCES = HERE.parent.parent / "app" / "sharedTest" / "resources"
SOURCE = RESOURCES / "near-life.json"
SPEC = HERE / "near-life-spec.json"
DATABASE = HERE / "tel-link-examples.kdbx"


def main() -> int:
    source = json.loads(SOURCE.read_text(encoding="utf-8"))
    values = {v["id"]: v for v in json.load(open(RESOURCES / "tel-values.json", encoding="utf8"))}
    cases = []
    for path in sorted(glob.glob(str(RESOURCES / "tel-cases" / "*.json"))):
        cases += json.load(open(path, encoding="utf8"))
    code_cases = [c for c in cases if c["level"] == "code" and c.get("field", "url") == "url"]

    base = json.loads((HERE / "fixture-spec.json").read_text(encoding="utf-8"))
    entries = []
    for item in source["entries"]:
        text = values[item["value"]]["value"]
        group = [c for c in code_cases if c["value"] == item["value"]]
        if not group:
            print(f"no code case for {item['value']} ({item['title']})", file=sys.stderr)
            return 1
        links = group[0]["expected"]["links"]
        expected = ("Underlined: " + ", ".join(repr(link["text"]) for link in links) + ". The rest is plain."
                    if links else "Nothing is underlined.")
        entry = {"id": item["title"], "field": "url", "value": text, "links": links,
                 "notes": f"{item['what']} ({item['value']})", "expected": expected}
        if any(link["target"].lower().startswith("tel:") for link in links):
            entry["scenarios"] = ["UI-LINK", "UI-TAP", "UI-LONGPRESS", "UI-CALL"]
        entries.append(entry)

    spec = {k: v for k, v in base.items() if k not in ("entries", "description")}
    spec["description"] = ("Generated by make_near_life.py from near-life.json; do not edit. The near-life "
                           "database: " + source["description"])
    spec["entries"] = entries
    SPEC.write_text(json.dumps(spec, indent=2, ensure_ascii=True) + "\n", encoding="utf-8", newline="\n")
    print(f"{SPEC.name}: {len(entries)} entries")

    if not DATABASE.exists():
        create_database(str(DATABASE), password=spec["database"]["password"])
        print(f"created {DATABASE.name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
